"""Added date column to Event model

Revision ID: 30894c8a2474
Revises: 8c06d8291d05
Create Date: 2024-06-26 21:55:33.306063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30894c8a2474'
down_revision = '8c06d8291d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
